# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main_server/infrastructure/grpc/ai_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'main_server/infrastructure/grpc/ai_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2main_server/infrastructure/grpc/ai_inference.proto\x12\x0c\x61i_inference\"\x07\n\x05\x45mpty\"\xb3\x01\n\x0fInferenceResult\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x41\n\x10object_detection\x18\x02 \x01(\x0b\x32%.ai_inference.ObjectDetectionResponseH\x00\x12\x41\n\x10\x66\x61\x63\x65_recognition\x18\x03 \x01(\x0b\x32%.ai_inference.FaceRecognitionResponseH\x00\x42\x08\n\x06result\" \n\x0cImageRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\"j\n\x17ObjectDetectionResponse\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12&\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x19.ai_inference.BoundingBox\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"l\n\x17\x46\x61\x63\x65RecognitionResponse\x12\x13\n\x0bperson_type\x18\x01 \x01(\t\x12\x18\n\x0b\x65mployee_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x42\x0e\n\x0c_employee_id2\x86\x02\n\x0b\x41IInference\x12R\n\rDetectObjects\x12\x1a.ai_inference.ImageRequest\x1a%.ai_inference.ObjectDetectionResponse\x12S\n\x0eRecognizeFaces\x12\x1a.ai_inference.ImageRequest\x1a%.ai_inference.FaceRecognitionResponse\x12N\n\x16StreamInferenceResults\x12\x13.ai_inference.Empty\x1a\x1d.ai_inference.InferenceResult0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_server.infrastructure.grpc.ai_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=68
  _globals['_EMPTY']._serialized_end=75
  _globals['_INFERENCERESULT']._serialized_start=78
  _globals['_INFERENCERESULT']._serialized_end=257
  _globals['_IMAGEREQUEST']._serialized_start=259
  _globals['_IMAGEREQUEST']._serialized_end=291
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_start=293
  _globals['_OBJECTDETECTIONRESPONSE']._serialized_end=399
  _globals['_BOUNDINGBOX']._serialized_start=401
  _globals['_BOUNDINGBOX']._serialized_end=467
  _globals['_FACERECOGNITIONRESPONSE']._serialized_start=469
  _globals['_FACERECOGNITIONRESPONSE']._serialized_end=577
  _globals['_AIINFERENCE']._serialized_start=580
  _globals['_AIINFERENCE']._serialized_end=842
# @@protoc_insertion_point(module_scope)
